import type { NextPage } from 'next';
import Head from 'next/head';
import { useEffect, useState } from 'react';

const Home: NextPage = () => {
  const [converted, setConverted] = useState<any>(0);
  const [price, setPrice] = useState<number | null>(null);
  const onChangeHandler = (event: any) => {
    const val = ((event.target.value / price!) * 100_000_000).toFixed(0);
    const formatted = new Intl.NumberFormat('en-US').format(+val);
    setConverted(formatted);
  };

  useEffect(() => {
    fetch('/api/price')
      .then((res) => res.json())
      .then((data) => {
        setPrice(data);
      });
  }, []);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='h-screen flex flex-col items-center bg-gray-800 text-white'>
        <h1 className='text-4xl p-8'>ManySats</h1>
        <div className='h-full flex justify-center items-center flex-col'>
          <div className='w-full flex my-8'>
            <input
              className='text-center bg-gray-800 border-b border-white outline-none'
              onChange={onChangeHandler}
            ></input>
          </div>
          <div className='w-full block my-8'>
            <div className='flex justify-center'>{converted}</div>
          </div>
        </div>
      </main>
    </div>
  );
};

export default Home;
